services:
    by.page_cache.listener:
        class: BigyouthPageCacheBundle\Listener\PageCacheListener
        arguments:  [@by.page_cache, @security.token_storage]
        tags:
            -  { name: kernel.event_subscriber }
